server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 1024

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crake.cojtlpgcxusg.ap-northeast-2.rds.amazonaws.com:3306/crake?characterEncoding=utf8&characterSetResults=utf8&useUnicode=true&autoReconnect=true&allowMultiQueries=true&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    sql-script-encoding: UTF-8
    username: "admin"
    password: "!Tla3478"
  security:
    user:
      name: admin
      password: admin1234
      roles:
        - ceo
        - user
        - manager
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true
  data:
    web:
      pageable:
        max-page-size: 500
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 30MB
      file-size-threshold: 2MB
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        #globally_quoted_identifiers: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  task:
    execution:
      pool:
        core-size: 8
        max-size: 128
        queue-capacity: 128
        allow-core-thread-timeout: true
        keep-alive: 30s
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
